import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
  advance: [{ type: "autogenerated", dirName: "advance" }],
  basic: [{ type: "autogenerated", dirName: "basic" }],
  devops: [{ type: "autogenerated", dirName: "devops" }],
  frame: [{ type: "autogenerated", dirName: "frame" }],
  // frame: [
  //   {
  //     type: "category",
  //     label: "前端框架",
  //     link: {
  //       type: "generated-index",
  //       description:
  //         "你能看到这里说明你已经可以独挡一面完成项目了，加油，”童鞋“",
  //       slug: "/category/docusaurus-guides",
  //       keywords: ["前端框架"],
  //       image: "/img/docusaurus.png",
  //     },
  //     items: [
  //       {
  //         type: "category",
  //         label: "React",
  //         link:{
  //           type: "generated-index",
  //         },
  //         items: [{ type: "autogenerated", dirName: "frame/react" }],
  //       },
  //       {
  //         type: "category",
  //         label: "Vue",
  //         link:{
  //           type: "generated-index",
  //         },
  //         items: [{ type: "autogenerated", dirName: "frame/vue" }],
  //       },
  //     ],
  //   },
  // ],
  network: [{ type: "autogenerated", dirName: "network" }],
  pkg: [{ type: "autogenerated", dirName: "pkg" }],
  server: [{ type: "autogenerated", dirName: "server" }],
  browser: [{ type: "autogenerated", dirName: "software/browser" }],
};

export default sidebars;
